import { useState } from 'react';
import { Pencil, Trash2, XCircle, Loader2 } from 'lucide-react';

const InstituteERPBatches = ({
  batches = [],
  courses = [],
  newBatch,
  setNewBatch,
  handleCreateBatch,
  handleUpdateBatch,
  handleDeleteBatch
}) => {
  const [editingBatch, setEditingBatch] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [editForm, setEditForm] = useState({
    name: '',
    startDate: '',
    seats: ''
  });

  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 6;
  const totalPages = Math.ceil(batches.length / itemsPerPage) || 1;
  const paginatedBatches = batches.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  // Handle setting edit form when selecting a batch to edit
  const startEdit = (batch) => {
    setEditingBatch(batch);
    setEditForm({
      name: batch.name || '',
      startDate: batch.startDate ? batch.startDate.split('T')[0] : '',
      seats: batch.seats || '5'
    });
  };

  const cancelEdit = () => {
    setEditingBatch(null);
    setEditForm({ name: '', startDate: '', seats: '' });
  };

  const onEditSubmit = async (e) => {
    e.preventDefault();
    if (submitting) return;
    if (!editForm.name || !editForm.startDate) {
      alert('Please fill in the batch name and commencement date.');
      return;
    }
    
    setSubmitting(true);
    try {
      if (handleUpdateBatch) {
        const batchId = editingBatch._id || editingBatch.id;
        await handleUpdateBatch(batchId, {
          name: editForm.name,
          startDate: editForm.startDate,
          seats: editForm.seats ? Number(editForm.seats) : undefined
        });
      }
      cancelEdit();
    } finally {
      setSubmitting(false);
    }
  };

  const onSubmit = async (e) => {
    if (submitting) return;
    setSubmitting(true);
    try {
      await handleCreateBatch(e);
    } finally {
      setSubmitting(false);
    }
  };



  const selectedCourseObj = courses.find(c => (c.id || c._id) === newBatch.courseId);
  const courseCodePrefix = selectedCourseObj ? (selectedCourseObj.courseCode || selectedCourseObj.courseName || selectedCourseObj.name || '').replace(/[^A-Za-z0-9]/g, '').slice(0, 4).toUpperCase() : 'SEMI';
  const batchYear = newBatch.startDate ? new Date(newBatch.startDate).getFullYear() : 2026;
  const existingCountForCourse = batches.filter(b => (b.course?._id || b.course) === newBatch.courseId && b.year === batchYear).length;
  const autoGeneratedLetter = String.fromCharCode(65 + (existingCountForCourse % 26));
  const previewBatchName = selectedCourseObj ? `${courseCodePrefix}-${batchYear}-Batch ${autoGeneratedLetter}` : 'Select course & date';

  return (
    <div className="space-y-8 animate-in fade-in duration-200 text-left">
      <div>
        <h2 className="text-2xl font-black text-gray-900">Batches</h2>
        <p className="text-xs text-gray-500 mt-1">Configure academic session batches under standardized SEMI courses</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* 1. CREATION / EDIT PANEL */}
        <div className="bg-white border border-gray-200/80 rounded-3xl p-6 shadow-sm space-y-6 h-fit">
          <div className="flex justify-between items-center border-b border-gray-100 pb-3">
            <div>
              <h3 className="text-sm font-black text-gray-900 uppercase tracking-wider">
                {editingBatch ? 'Edit Batch' : 'Create Batch'}
              </h3>
              {!editingBatch && (
                <span className="text-[10px] text-blue-600 font-bold uppercase tracking-wider block mt-0.5">
                  Automated Naming Convention
                </span>
              )}
            </div>
            {editingBatch && (
              <button 
                type="button" 
                onClick={cancelEdit}
                className="text-xs font-bold text-gray-400 hover:text-gray-600 flex items-center gap-1 cursor-pointer"
              >
                <XCircle className="w-3.5 h-3.5" />
                Cancel Edit
              </button>
            )}
          </div>
          
          <form onSubmit={editingBatch ? onEditSubmit : onSubmit} className="space-y-4">
            <div>
              <label className="block text-xs uppercase font-extrabold tracking-wider text-gray-500 mb-2">Select Course *</label>
              <select
                required
                disabled={!!editingBatch}
                value={editingBatch ? (editingBatch.course?._id || editingBatch.course || editingBatch.courseId || '') : (newBatch.courseId || '')}
                onChange={(e) => {
                  if (!editingBatch) {
                    setNewBatch({ ...newBatch, courseId: e.target.value });
                  }
                }}
                className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-gray-900 focus:outline-none focus:bg-white focus:border-blue-500 transition-all text-xs font-bold disabled:opacity-75 disabled:cursor-not-allowed"
              >
                <option value="">-- Choose Standardized Course --</option>
                {courses.map(course => (
                  <option key={course.id || course._id} value={course.id || course._id}>
                    {course.courseName || course.name} ({course.courseCode || 'SEMI'})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs uppercase font-extrabold tracking-wider text-gray-500 mb-2">Commencement Date *</label>
              <input
                type="date"
                required
                value={editingBatch ? editForm.startDate : newBatch.startDate}
                onChange={(e) => {
                  if (editingBatch) {
                    setEditForm({ ...editForm, startDate: e.target.value });
                  } else {
                    setNewBatch({ ...newBatch, startDate: e.target.value });
                  }
                }}
                className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-gray-900 focus:outline-none focus:bg-white focus:border-blue-500 transition-all text-xs font-bold"
              />
            </div>

            <div>
              <div className="flex justify-between items-center mb-2">
                <label className="block text-xs uppercase font-extrabold tracking-wider text-gray-500">
                  Official Batch Name
                </label>
                <span className="text-[10px] font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded-full border border-blue-200">
                  Auto Generated
                </span>
              </div>
              {editingBatch ? (
                <input
                  type="text"
                  required
                  placeholder="e.g. DEM-2026-Batch A"
                  value={editForm.name}
                  onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                  className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-gray-900 font-mono font-bold focus:outline-none focus:bg-white focus:border-blue-500 transition-all text-xs"
                />
              ) : (
                <div className="w-full px-4 py-3 bg-blue-50/50 border border-blue-200 rounded-xl text-blue-900 font-mono font-black text-xs flex items-center justify-between">
                  <span>{previewBatchName}</span>
                  <span className="text-[9px] uppercase font-bold text-blue-500 bg-white px-2 py-0.5 rounded border border-blue-100">Standardized</span>
                </div>
              )}
              <p className="text-[10px] text-gray-400 mt-1 italic">
                Batches automatically follow the SEMI official naming rule: [CourseCode]-[Year]-Batch [Letter].
              </p>
            </div>



            <button
              type="submit"
              disabled={submitting}
              className={`w-full py-3.5 text-white font-extrabold rounded-xl transition-all shadow-md text-xs uppercase tracking-wider cursor-pointer flex items-center justify-center gap-2 ${
                editingBatch 
                  ? 'bg-indigo-600 hover:bg-indigo-700 shadow-indigo-500/10' 
                  : 'bg-blue-600 hover:bg-blue-700 shadow-blue-500/10'
              } disabled:opacity-60 disabled:cursor-not-allowed disabled:hover:bg-blue-600`}
            >
              {submitting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  {editingBatch ? 'Saving Changes...' : 'Creating Batch...'}
                </>
              ) : (
                editingBatch ? 'Save Changes' : 'Create Standardized Batch'
              )}
            </button>
          </form>
        </div>
 
        {/* 2. ACTIVE BATCHES LIST */}
        <div className="bg-white border border-gray-200/80 rounded-3xl p-6 shadow-sm lg:col-span-2 space-y-6">
          <h3 className="text-sm font-black text-gray-900 uppercase tracking-wider border-b border-gray-100 pb-3">Active Batches Registry</h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 font-semibold text-xs text-gray-600">
            {paginatedBatches.map((batch) => {
              const ratio = Math.min(100, Math.floor(((batch.activeFellows || 0) / parseInt(batch.seats || 5, 10)) * 100));
              const isEditingThis = editingBatch && (editingBatch._id === batch._id || editingBatch.id === batch.id);
              const courseDisplayName = batch.course?.name || batch.course?.courseName || batch.courseName || (typeof batch.course === 'string' ? batch.course : '');

              return (
                <div 
                  key={batch.id || batch._id} 
                  className={`border rounded-2xl p-5 transition-all duration-200 bg-gray-50/20 shadow-sm flex flex-col justify-between gap-4 ${
                    isEditingThis 
                      ? 'border-indigo-500 ring-2 ring-indigo-500/10' 
                      : 'border-gray-150 hover:border-gray-300'
                  }`}
                >
                  <div className="flex justify-between items-start">
                    <div className="space-y-1 text-left">
                      <span className="bg-blue-50 text-blue-700 text-[10px] font-bold px-2 py-0.5 rounded border border-blue-100 block w-fit font-mono">
                        BATCH ID: #{String(batch.id || batch._id).substring(0, 8).toUpperCase()}
                      </span>
                      <h4 className="text-base font-black text-gray-800 pt-1.5 leading-tight">{batch.name}</h4>
                      {courseDisplayName && (
                        <span className="bg-purple-50 text-purple-700 text-[10px] font-bold px-2 py-0.5 rounded border border-purple-100 block w-fit mt-1.5">
                          Course: {courseDisplayName}
                        </span>
                      )}
                      <span className="text-[10px] text-gray-500 font-semibold block mt-1">Commencement: {batch.startDate ? batch.startDate.split('T')[0] : 'N/A'}</span>
                    </div>

                    {/* Actions buttons */}
                    <div className="flex items-center gap-1 bg-white border border-slate-100 shadow-sm rounded-xl p-1">
                      <button
                        type="button"
                        onClick={() => startEdit(batch)}
                        className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-slate-50 rounded-lg transition-all cursor-pointer"
                        title="Edit Batch"
                      >
                        <Pencil className="w-3.5 h-3.5" />
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDeleteBatch(batch._id || batch.id)}
                        className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-slate-50 rounded-lg transition-all cursor-pointer"
                        title="Delete Batch"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>

                  <div className="space-y-2 text-left">
                    <div className="flex justify-between items-center text-[10px] font-bold text-gray-500">
                      <span>Seat Utilization:</span>
                      <span className="text-gray-800">{batch.activeFellows || 0} / {batch.seats || 5} Fellows</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-1.5 overflow-hidden">
                      <div className="bg-blue-600 h-1.5 rounded-full transition-all duration-500" style={{ width: `${ratio}%` }}></div>
                    </div>
                  </div>
                </div>
              );
            })}
            {batches.length === 0 && (
              <div className="col-span-2 py-16 text-center text-slate-400 font-medium bg-slate-50/50 rounded-2xl border border-dashed border-slate-200">
                No active batches registered. Configure one using the creation panel.
              </div>
            )}
          </div>
          
          {/* Pagination Controls */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between pt-4 mt-2 border-t border-gray-100">
              <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">
                Showing {((currentPage - 1) * itemsPerPage) + 1} to {Math.min(currentPage * itemsPerPage, batches.length)} of {batches.length} Batches
              </span>
              <div className="flex gap-1">
                <button
                  onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                  disabled={currentPage === 1}
                  className="px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-bold text-slate-600 hover:bg-slate-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Prev
                </button>
                <div className="flex items-center px-3 py-1.5 rounded-lg bg-slate-50 border border-slate-200 text-xs font-bold text-blue-600 shadow-sm">
                  {currentPage} / {totalPages}
                </div>
                <button
                  onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                  disabled={currentPage === totalPages}
                  className="px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-bold text-slate-600 hover:bg-slate-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Next
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default InstituteERPBatches;