export const APP_CONSTANTS = {
  ATTENDANCE_MIN_PERCENTAGE: Number(process.env.ATTENDANCE_MIN_PERCENTAGE) || 75,
  STUDENT_REMITTANCE_FEE_INR: Number(process.env.STUDENT_REMITTANCE_FEE_INR) || 50000,
  REVALUATION_FEE_PER_SUBJECT_INR: Number(process.env.REVALUATION_FEE_PER_SUBJECT_INR) || 500,
  INSPECTION_FEE_INR: Number(process.env.INSPECTION_FEE_INR) || 25000,
  DEFAULT_APPROVED_SEATS: Number(process.env.DEFAULT_APPROVED_SEATS) || 5,
};
